from app.providers.base import LLMProvider


class MockProvider(LLMProvider):
    def generate(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        return f"""
# Mock Lesson

This lesson was generated by the mock provider.

## Request

{user_prompt}

## Overview

This confirms that the full application path works without contacting an
external model provider.

## Review Questions

1. Did the route call the tutor service?
2. Did the tutor service call the provider?
3. Did the resulting Markdown render correctly?
""".strip()